### PR TITLE
Add new event with call for paper

### PR DESCRIPTION
**Pull request by marquinhusgoncalves-zz**

### CODE REVIEW

**Comment by alinebastos** [comment]
O C4P do FrontinSampa já acabou =/

**Comment by marquinhusgoncalves-zz** [comment]
CFP closes at | June 04, 2018 23:06 UTC | June 04, 2018 20:06 (Local)
https://www.papercall.io/frontinsampa2018
:thinking:

**Comment by alinebastos** [comment]
Ué, era até ontem, que estranho, hehe, vou fazer o merge ^^

**Comment by marquinhusgoncalves-zz** [comment]
:rocket:

**Pull request merged**
